services:

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=todo.db
      - ConnectionStrings__SqliteConnection=Data Source=todo.db
    volumes:
      - todo_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - todo-network

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  todo_data:
    driver: local

networks:
  todo-network:
    driver: bridge
